name: Inspect

on: push

permissions:
  contents: read

env:
  DEBUG: yes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Show make
      run: |
        docker build -t localhost/shell-samples .
    - name: Inspect
      run: |
        docker run --rm -t localhost/shell-samples make inspect
