name: Tests

on: push

permissions:
  contents: read

env:
  DEBUG: yes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Show make
      run: |
        make show-make
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make check
